services: 

  web: 
      build: .
      ports:
        - "8000:8000"
      volumes:
        - .:/var/www
      extra_hosts:
        - host.docker.internal:host-gateway
  db:
      image: mariadb:10.6
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: Afpa1234
      ports:
        - "3307:3306"
      volumes:
      - mariadb_data:/var/lib/mysql

 # phpmyadmin: 
 #     image: phpmyadmin
 #     restart: always
 #     ports:
 #       - "8080:80"
 #     environment:
 #       - PMA_ARBITRARY=1

  mailhog:
      image: mailhog/mailhog:latest
      restart: always
      ports:
        - "1025:1025"
        - "8025:8025"
     
volumes: 
  mariadb_data: